### ISSUE TITLE
KIF tests

### ISSUE THREAD

**Issue by larcus94** [larcus94/ImagePickerSheetController#21]
In order to test the component thoroughly, KIF tests need to be written. Help would be appreciated :)

**Comment by larcus94** [comment]
Added KIF tests. Rewriting this using Apple's new UI test now...

**Comment by joemasilotti** [comment]
Is there an active branch I can track to see progress of the UI Tests? I'm very interested to see how others are using the new framework.

**Comment by larcus94** [comment]
@joemasilotti I'm now using KIF instead of XCTest. You can see some of the these tests already in the test suite

**Comment by joemasilotti** [comment]
So no iOS 8 UI Testing?

**Comment by larcus94** [comment]
@joemasilotti yes, with KIF though
