### ISSUE TITLE
Scrolling not smooth at all on iPhone 5.

### ISSUE THREAD

**Issue by csilouanos** [larcus94/ImagePickerSheetController#24]
So the problem on my end is that when I tested the example on iPhone 5, iOS 8.3 the scrolling, between the images, was not smooth at all. In iMessage is very smooth. 

Thank you!

**Comment by larcus94** [comment]
You mentioned that you replaced the images with labels which still resulted in sluggish animations. Did you already figure out why this is? I obviously tried this on some devices, one of which was the iPod 4 gen which worked fairly well...

**Comment by csilouanos** [comment]
No man I didn't figure out why that happens.. I don't think it's my phone because iMessages image picker works as expected. I tried creating a new project and pod your library but I faced the same issue.

**Comment by csilouanos** [comment]
By the way, sorry for asking, but how did you test it on iPod 4? The highest version that is supported by this model is iOS 6.

**Comment by larcus94** [comment]
@csilouanos 5 gen whatever, the one that supports iOS 8. That's so weird though. Did you do the time profiling?

**Comment by csilouanos** [comment]
I tried it but for some reason I can't start the time profiling. Is the counters tool isn't it?

**Comment by csilouanos** [comment]
Hey man, so I found the issue! The problem is that when user has hundreds of images (in his device) the scroll is getting bad. On my device I have around 1600 images! That's why the problem exists.

On top of that, I think this library suppose to fetch only the recent images. That's why, maybe, on your end (even with iPod) was working great. 

In my opinion I think you should change that bit of code where you are fetching the images in the first place. So the method fetchAssets() should fetch the number of images depending maybe on a constant that the developer can set.

Even Apple is not doing that (fetching all the user's images). What they are doing, is that they fetched just the recent images! 

I changes that but of code on your library and on my phone finally works great! 

If I have any other issue I will let you know! Thank you very much for your time and your help!

**Comment by larcus94** [comment]
@csilouanos Ooh, that's why! Yeah I always only have a couple hundred images. Will fix this tonight! Thanks for your info :)

**Comment by csilouanos** [comment]
My pleasure!

**Comment by larcus94** [comment]
Okay, restricted the loaded assets to 50. I published v0.1.2 that you should update to via Cocoapods or Carthage, whatever you like :) Thanks again for pointing this out.
