### ISSUE TITLE
Using this with Objective C

### ISSUE THREAD

**Issue by bennettl** [larcus94/ImagePickerSheetController#28]
Hello,

I was wondering how can I integrate this with my current objective c code?

Best,
Bennett

**Comment by larcus94** [comment]
This should work just fine if you use Cocoapods or Carthage.

**Comment by larcus94** [comment]
This should work just fine if you use Cocoapods or Carthage. What problems are you running into?

**Comment by bennettl** [comment]
Not sure exactly how to import the Swift base framework into objective c code. I tried using #import <ImagePickerSheetController/ImagePickerSheetController.h> but it doesn't seem to work.

**Comment by larcus94** [comment]
[This](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html) should help you

**Comment by rishabhtayal** [comment]
@larcus94 Getting this error in objective-c project. 

[!] Pods written in Swift can only be integrated as frameworks; this feature is still in beta. Add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: ImagePickerSheetController

**Comment by larcus94** [comment]
Then you're out of luck I'm afraid. Swift pods can only be added as a framework.

**Comment by chayan19** [comment]
Hi Larcus94
I have an objective c project.Could you please help me with the installation steps of this framework in the project.If you could share the steps it would be helpful.
