### ISSUE TITLE
iPhone 6 (iOS 8) CheckMark Position Issue

### ISSUE THREAD

**Issue by bennettl** [larcus94/ImagePickerSheetController#29]
Seems to be an issue with the bottom right circle being a little bit off to the right. I copy and pasted the code as is in my swift class. My xib file is using auto layout.
![ios simulator screen shot jun 15 2015 10 55 20 am](https://cloud.githubusercontent.com/assets/1672224/8166540/45bd2c02-134d-11e5-9f7e-4931bb93a41a.png)
![ios simulator screen shot jun 15 2015 10 55 25 am](https://cloud.githubusercontent.com/assets/1672224/8166539/45bcda36-134d-11e5-9225-03a1571b918e.png)
![ios simulator screen shot jun 15 2015 10 55 29 am](https://cloud.githubusercontent.com/assets/1672224/8166538/45bb76aa-134d-11e5-918f-8b2f89ba20fa.png)

**Comment by larcus94** [comment]
You forgot to add the resources. I'd suggest you to use CocoaPods or Carthage to use the module. Then you don't have to worry about it.
