### ISSUE TITLE
Error on integrating IPSC with carthage

### ISSUE THREAD

**Issue by hankbao** [larcus94/ImagePickerSheetController#31]
I'm trying to integrate IPSC with carthage. However the building process of IPSC involves all testing stuffs including Nimble/Quick/KIF and fails eventually when trying to build Quick. I suppose apps link against IPSC should not rely on its unit tests.

**Comment by larcus94** [comment]
@hankbao That's true indeed. AFAIK there's no way to specify dependencies for test purposes only with Carthage. I'll fix this on the weekend.

**Comment by larcus94** [comment]
@hankbao I've actually fixed this just now with tag `0.1.3` :) Hope this works better for you.

**Comment by hankbao** [comment]
@larcus94  Unfortunately, carthage still complains about KIF/Nimble/Quick and quits with errors as `0.1.3`.

`ImagePickerSheetControllerTests/KIFExtensions.swift:10:8: error: no such module 'KIF'`
`error: /tmp/ImagePickerSheetController/Carthage/             Checkouts/ImagePickerSheetController/Carthage/Build/iOS/Nimble.framework:       No such file or directory`
`error: /tmp/ImagePickerSheetController/Carthage/             Checkouts/ImagePickerSheetController/Carthage/Build/iOS/Quick.framework:       No such file or directory`
`error: /tmp/ImagePickerSheetController/Carthage/             Checkouts/ImagePickerSheetController/Carthage/Build/iOS/KIF.framework:       No such file or directory`

**Comment by larcus94** [comment]
Ups, yeah, forgot about that. Will fix that today. Sorry about that.

**Comment by larcus94** [comment]
Now it works :) Try it again with tag `0.1.3`.
