### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by matthewjdrover** [larcus94/ImagePickerSheetController#33]
Using the latest version when I run on my 5s and select 11 or more photos from my camera roll the app uses too much memory and crashes. Can the images be returned as reference, or can you return indexes in getSelectedImagesWithCompletion() and we can grab the high quality version and process it one at a time.

Thanks.

--------

2015-07-03 14:33:37.217 Example[15609:4906189] Connection to assetsd was interrupted or assetsd died
2015-07-03 14:33:37.623 Example[15609:4906072] Received memory warning.
2015-07-03 14:33:37.895 Example[15609:4906072] Received memory warning.

**Comment by larcus94** [comment]
@matthewjdrover Hi Matthew,
Thank you for filing this issue. I feel so silly that I haven't fixed this before. Anyways, I replaced the `getSelectedImagesWithCompletion()` method with a simple property called `selectedImageAssets`. This makes the API more flexible and fixes your issue as well :)
Just make sure to update to v0.1.5 now!
