### ISSUE TITLE
Error selecting image.

### ISSUE THREAD

**Issue by paterlini** [larcus94/ImagePickerSheetController#34]
Why when I select the picture select button does not work properly?
<img width="334" alt="2015-07-07 18 24 45" src="https://cloud.githubusercontent.com/assets/9257530/8549881/f1ee845a-24d5-11e5-8e9d-4528c368b61a.png">

**Comment by larcus94** [comment]
@paterlini How did you integrate the framework? Did you use carthage or cocoapods?

**Comment by paterlini** [comment]
I use cocapods in swift. 
<img width="307" alt="2015-07-08 0 50 19" src="https://cloud.githubusercontent.com/assets/9257530/8558208/5a87d72a-250b-11e5-8d97-55a9d0be3a90.png">

**Comment by larcus94** [comment]
@paterlini Right, I tried it to and doesn't work for me either. I'll fix this tonight!

**Comment by paterlini** [comment]
Okey! Thank you!

**Comment by larcus94** [comment]
This has to do with Cocoapods copying the image differently than Carthage. I couldn't find a fix for now. I'll try fixing it as soon as possible. Stay tuned!

**Comment by larcus94** [comment]
@paterlini Okay, managed to fix the issue today. Sorry for letting you wait so long. Just make sure to use version `0.1.6`.

**Comment by paterlini** [comment]
Ok. Thank you!!

**Comment by larcus94** [comment]
@paterlini Let me know if you run into any other issues! :)
