### ISSUE TITLE
Can't use with Xcode 7 GM

### ISSUE THREAD

**Issue by zhouzizi** [larcus94/ImagePickerSheetController#47]
pod 'ImagePickerSheetController', :git => 'https://github.com/larcus94/ImagePickerSheetController.git', :branch => 'ios9'
 
but have many error ,like
 Use of undeclared type 'SheetController'
 Use of unresolved identifier 'PreviewSupplementaryView'
 Use of unresolved identifier 'PreviewCollectionViewCell'

**Comment by larcus94** [comment]
Hm, I don't have tons of experience with cocoapods so I'm not quite sure if this is even supposed to work. But I guess it will once I update it?
