### ISSUE TITLE
can you recommend a component like this one that target from ios7.0

### ISSUE THREAD

**Issue by wealon** [larcus94/ImagePickerSheetController#48]
hi,
  can you recommend a component like this one that target from ios7.0

thank you

**Comment by larcus94** [comment]
Hm, not that I know of, I'm afraid. `ImagePickerSheetController` uses the `Photos` framework which is only available on iOS 8 and later so you'd have to use `AssetsLibrary` instead. I'm not planning to do that myself however, sorry.

**Comment by wealon** [comment]
thanks for you reply
