### ISSUE TITLE
crashed when I selected the collection cell on iPhone6.

### ISSUE THREAD

**Issue by jiaopen** [larcus94/ImagePickerSheetController#50]
error:
*** Assertion failure in -[UICollectionViewData validateLayoutInRect:]

ImagePickerSheetController.swift - line:287

**Comment by larcus94** [comment]
Which cell did you select exactly?

**Comment by jiaopen** [comment]
I selected the cell before it was enlarged, and I have fixed this bug by modified this func:

    public func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, referenceSizeForHeaderInSection section: Int) -> CGSize {
        let inset = 2.0 * collectionViewCheckmarkInset
        let imageWidth = PreviewSupplementaryView.checkmarkImage?.size.width ?? 0
        return CGSizeMake(imageWidth  + inset, tableViewEnlargedPreviewRowHeight - inset)
    }

**Comment by jiaopen** [comment]
It is verv strange, the bug only appear on my iPhone6(iOS9), there is no problem with other devices.
