### ISSUE TITLE
iOS 9 ,bug

### ISSUE THREAD

**Issue by zhouzizi** [larcus94/ImagePickerSheetController#56]
![image](https://cloud.githubusercontent.com/assets/9103749/10425009/bc45b954-7106-11e5-9650-e87976d9acab.png)

**Comment by zhouzizi** [comment]
so ugly..

**Comment by larcus94** [comment]
Would you mind elaborating?

**Comment by zhouzizi** [comment]
![image](https://cloud.githubusercontent.com/assets/9103749/10476875/1a737466-7284-11e5-8f6e-1ef895b94b7d.png)
this effect don't have blank space,it's perfect.
but in iOS 9 ，the cell can't fill the screenWidth
![image](https://cloud.githubusercontent.com/assets/9103749/10476885/2d4c57f6-7284-11e5-856b-87c78600854c.png)

**Comment by larcus94** [comment]
Uhm, I just replicated the iOS 9 design, so I'm not quite sure what you're what you want me to do?
