### ISSUE TITLE
CompileAssetsCatalog fails randomly

### ISSUE THREAD

**Issue by mbalex99** [larcus94/ImagePickerSheetController#58]
I get an error very randomly when trying to compile the asset catalog...

I don't seem to get any more information than this. Most of the time it passes compilation sometimes it fails...

```
The following build commands failed:
	CompileAssetCatalog /Users/greenhouse/tmp4ZakUq/build/Debug-iphoneos/ImagePickerSheetController.framework ImagePickerSheetController/ImagePickerSheetController/ImagePickerSheetController/Images.xcassets
(1 failure)


Build failed :|
Running xcodebuild failed```

**Comment by larcus94** [comment]
Uuuh, so sorry for not responding to this. Is this still an issue? I don't have any clue what is going on here tbh

**Comment by lferro9000** [comment]
On a completly unrelated project, i've the same issue. CompileAssetCatalog will fail to compile the icons / images at random.
